module Farscape.Tests.CodeRendererTests

open Xunit
open Farscape.Core.CodeAST
open Farscape.Core.CodeRenderer

[<Fact>]
let ``renderType handles Named types`` () =
    Assert.Equal("int32", renderType (Named "int32"))
    Assert.Equal("nativeint", renderType (Named "nativeint"))

[<Fact>]
let ``renderType handles Generic types`` () =
    Assert.Equal("nativeptr<byte>", renderType (Generic("nativeptr", Named "byte")))

[<Fact>]
let ``renderType handles Unit`` () =
    Assert.Equal("unit", renderType Unit)

[<Fact>]
let ``render LetBinding produces correct F# function`` () =
    let decl = Module("Test.Module", "test",
        [
            LetBinding("myFunc",
                [{ Name = "x"; Type = Named "int32" }; { Name = "y"; Type = Named "int32" }],
                Named "int32",
                DefaultOf (Named "int32"),
                [])
        ])
    let result = render decl
    Assert.Contains("let myFunc (x: int32) (y: int32) : int32 =", result)
    Assert.Contains("Unchecked.defaultof<int32>", result)

[<Fact>]
let ``render LetBinding with nativeptr param`` () =
    let decl = Module("Test.Module", "test",
        [
            LetBinding("strcpy",
                [{ Name = "dest"; Type = Generic("nativeptr", Named "byte") }
                 { Name = "src"; Type = Generic("nativeptr", Named "byte") }],
                Generic("nativeptr", Named "byte"),
                DefaultOf (Generic("nativeptr", Named "byte")),
                [])
        ])
    let result = render decl
    Assert.Contains("let strcpy (dest: nativeptr<byte>) (src: nativeptr<byte>) : nativeptr<byte> =", result)

[<Fact>]
let ``render LiteralBinding produces Literal attribute`` () =
    let decl = Module("Test.Module", "test",
        [ LiteralBinding("EXIT_SUCCESS", "0") ])
    let result = render decl
    Assert.Contains("[<Literal>]", result)
    Assert.Contains("let EXIT_SUCCESS = 0", result)

[<Fact>]
let ``render EnumType produces F# enum`` () =
    let decl = Module("Test.Module", "test",
        [ EnumType("Color", [("Red", 0L); ("Green", 1L); ("Blue", 2L)], Some "A color enum", false) ])
    let result = render decl
    Assert.Contains("type Color =", result)
    Assert.Contains("| Red = 0L", result)
    Assert.Contains("| Green = 1L", result)
    Assert.Contains("| Blue = 2L", result)
    Assert.Contains("/// A color enum", result)
    Assert.DoesNotContain("[<System.Flags>]", result)

[<Fact>]
let ``render EnumType with Flags emits System.Flags attribute`` () =
    let decl = Module("Test.Module", "test",
        [ EnumType("Perms", [("Read", 1L); ("Write", 2L); ("Execute", 4L)], Some "Permission flags", true) ])
    let result = render decl
    Assert.Contains("[<System.Flags>]", result)
    Assert.Contains("type Perms =", result)
    Assert.Contains("| Read = 1L", result)
    Assert.Contains("/// Permission flags", result)

[<Fact>]
let ``render RecordType produces F# record`` () =
    let decl = Module("Test.Module", "test",
        [ RecordType("Point", [("x", Named "int32"); ("y", Named "int32")], Some "A 2D point", []) ])
    let result = render decl
    Assert.Contains("type Point = {", result)
    Assert.Contains("x: int32", result)
    Assert.Contains("y: int32", result)
    Assert.Contains("/// A 2D point", result)

[<Fact>]
let ``render Module produces header comment`` () =
    let decl = Module("Fidelity.libc.Memory", "Fidelity binding for libc", [])
    let result = render decl
    Assert.Contains("module Fidelity.libc.Memory", result)
    Assert.Contains("Generated by Farscape", result)
    Assert.Contains("Fidelity binding for libc", result)

[<Fact>]
let ``render XmlDoc produces triple-slash comment`` () =
    let decl = Module("Test", "test",
        [ XmlDoc "void foo(int x)" ])
    let result = render decl
    Assert.Contains("/// void foo(int x)", result)

[<Fact>]
let ``render zero-param function uses unit`` () =
    let decl = Module("Test", "test",
        [ LetBinding("abort", [], Unit, DefaultOf Unit, []) ])
    let result = render decl
    Assert.Contains("let abort () : unit =", result)

[<Fact>]
let ``render LetBinding with attributes produces attribute lines`` () =
    let decl = Module("Test", "test",
        [ LetBinding("memcpy",
            [{ Name = "dest"; Type = Named "nativeint" }
             { Name = "src"; Type = Named "nativeint" }
             { Name = "n"; Type = Named "nativeint" }],
            Named "nativeint",
            DefaultOf (Named "nativeint"),
            ["FidelityExtern(\"libc\", \"memcpy\")"]) ])
    let result = render decl
    Assert.Contains("[<FidelityExtern(\"libc\", \"memcpy\")>]", result)
    Assert.Contains("let memcpy (dest: nativeint) (src: nativeint) (n: nativeint) : nativeint =", result)
