[library]
header = "/usr/include/glib-2.0/glib-object.h"
include_paths = ["/usr/include/glib-2.0", "/usr/lib/glib-2.0/include", "/usr/include/sysprof-6"]
name = "gobject"
pkg_config = ["gobject-2.0"]

[output]
directory = "./gobject-bindings"
mode = "fidelity"

[[namespace]]
description = "Functions with prefix 'glib'"
library = "gobject"
name = "Fidelity.gobject.Glib"
prefixes = ["glib"]

[[namespace]]
description = "Ungrouped functions"
functions = [
    "g_binding_flags_get_type",
    "g_binding_get_type",
    "g_binding_get_flags",
    "g_binding_get_source",
    "g_binding_dup_source",
    "g_binding_get_target",
    "g_binding_dup_target",
    "g_binding_get_source_property",
    "g_binding_get_target_property",
    "g_binding_unbind",
    "g_object_bind_property",
    "g_object_bind_property_full",
    "g_object_bind_property_with_closures",
    "g_binding_group_get_type",
    "g_binding_group_new",
    "g_binding_group_dup_source",
    "g_binding_group_set_source",
    "g_binding_group_bind",
    "g_binding_group_bind_full",
    "g_binding_group_bind_with_closures",
    "g_enum_get_value",
    "g_enum_get_value_by_name",
    "g_enum_get_value_by_nick",
    "g_flags_get_first_value",
    "g_flags_get_value_by_name",
    "g_flags_get_value_by_nick",
    "g_enum_to_string",
    "g_flags_to_string",
    "g_value_set_enum",
    "g_value_get_enum",
    "g_value_set_flags",
    "g_value_get_flags",
    "g_enum_register_static",
    "g_flags_register_static",
    "g_enum_complete_type_info",
    "g_flags_complete_type_info",
    "g_unicode_break_type_get_type",
    "g_unicode_script_get_type",
    "g_normalize_mode_get_type",
    "g_param_spec_char",
    "g_param_spec_uchar",
    "g_param_spec_boolean",
    "g_param_spec_int",
    "g_param_spec_uint",
    "g_param_spec_long",
    "g_param_spec_ulong",
    "g_param_spec_int64",
    "g_param_spec_uint64",
    "g_param_spec_unichar",
    "g_param_spec_enum",
    "g_param_spec_flags",
    "g_param_spec_float",
    "g_param_spec_double",
    "g_param_spec_string",
    "g_param_spec_param",
    "g_param_spec_boxed",
    "g_param_spec_pointer",
    "g_param_spec_value_array",
    "g_param_spec_object",
    "g_param_spec_override",
    "g_param_spec_gtype",
    "g_param_spec_variant",
    "g_signal_group_get_type",
    "g_signal_group_new",
    "g_signal_group_set_target",
    "g_signal_group_dup_target",
    "g_signal_group_block",
    "g_signal_group_unblock",
    "g_signal_group_connect_closure",
    "g_signal_group_connect_object",
    "g_signal_group_connect_data",
    "g_signal_group_connect",
    "g_signal_group_connect_after",
    "g_signal_group_connect_swapped",
    "g_source_set_dummy_callback",
    "g_type_module_get_type",
    "g_type_module_use",
    "g_type_module_unuse",
    "g_type_module_set_name",
    "g_type_module_register_type",
    "g_type_module_add_interface",
    "g_type_module_register_enum",
    "g_type_module_register_flags",
    "g_type_plugin_get_type",
    "g_type_plugin_use",
    "g_type_plugin_unuse",
    "g_type_plugin_complete_type_info",
    "g_type_plugin_complete_interface_info",
    "g_value_array_get_type",
    "g_value_array_get_nth",
    "g_value_array_new",
    "g_value_array_free",
    "g_value_array_copy",
    "g_value_array_prepend",
    "g_value_array_append",
    "g_value_array_insert",
    "g_value_array_remove",
    "g_value_array_sort",
    "g_value_array_sort_with_data",
    "g_value_get_char",
    "g_value_set_schar",
    "g_value_get_schar",
    "g_value_set_uchar",
    "g_value_get_uchar",
    "g_value_set_boolean",
    "g_value_get_boolean",
    "g_value_set_int",
    "g_value_get_int",
    "g_value_set_uint",
    "g_value_get_uint",
    "g_value_set_long",
    "g_value_get_long",
    "g_value_set_ulong",
    "g_value_get_ulong",
    "g_value_set_int64",
    "g_value_get_int64",
    "g_value_set_uint64",
    "g_value_get_uint64",
    "g_value_set_float",
    "g_value_get_float",
    "g_value_set_double",
    "g_value_get_double",
    "g_value_set_string",
    "g_value_set_static_string",
    "g_value_set_interned_string",
    "g_value_get_string",
    "g_value_dup_string",
    "g_value_steal_string",
    "g_value_set_pointer",
    "g_value_get_pointer",
    "g_gtype_get_type",
    "g_value_set_gtype",
    "g_value_get_gtype",
    "g_value_set_variant",
    "g_value_take_variant",
    "g_value_get_variant",
    "g_value_dup_variant",
    "g_pointer_type_register_static",
    "g_strdup_value_contents",
    "g_value_take_string",
    "g_value_set_string_take_ownership",
]
library = "gobject"
name = "Fidelity.gobject.Core"
prefixes = []
