namespace Farscape.Core

open System.Text
open CodeAST
open ActivePatterns

/// Renders FsDecl AST nodes to F# source code strings.
///
/// This is the ONLY module in Farscape that uses StringBuilder.
/// Every other module produces FsDecl values: typed, inspectable, testable.
module CodeRenderer =

    /// Render an FsType to its F# string representation
    let rec renderType = function
        | Named n -> n
        | Generic (outer, inner) -> $"{outer}<{renderType inner}>"
        | Generic2 (outer, a, b) -> $"{outer}<{renderType a}, {renderType b}>"
        | Unit -> "unit"

    /// Render an FsParam to "(name: type)" form
    let renderParam (p: FsParam) = $"({cleanParamName p.Name}: {renderType p.Type})"

    /// Render an FsExpr to its F# string representation.
    /// The indent parameter is the continuation indent for multi-line expressions.
    let rec renderExpr (indent: string) = function
        | NativeZeroed -> "NativeDefault.zeroed ()"
        | FunctionCall (mod', name, args) ->
            let argStr = args |> List.map (renderArg indent) |> String.concat " "
            if mod' = "" then $"{name} {argStr}"
            else $"{mod'}.{name} {argStr}"
        | Identifier name -> name
        | TypeConversion (target, expr) -> $"{target} ({renderExpr indent expr})"
        | MethodCall (expr, method') -> $"{method'} ({renderExpr indent expr})"
        | IfThenElse (cond, thenE, elseE) ->
            $"if {renderExpr indent cond} then {renderExpr indent thenE}\n{indent}else {renderExpr indent elseE}"
        | Comparison (left, op, right) -> $"{renderExpr indent left} {op} {renderExpr indent right}"
        | Literal s -> s
        | ResultOk expr ->
            match expr with
            | Identifier _ | Literal _ -> $"Ok {renderExpr indent expr}"
            | _ -> $"Ok ({renderExpr indent expr})"
        | ResultError expr ->
            match expr with
            | Identifier _ | Literal _ -> $"Error {renderExpr indent expr}"
            | _ -> $"Error ({renderExpr indent expr})"
        | LetIn (name, binding, body) ->
            match binding with
            | MatchExpr _ ->
                // Put match on new line with extra indent so CCS doesn't confuse
                // match arms with subsequent let bindings
                let innerIndent = indent + "    "
                $"let {name} =\n{innerIndent}{renderExpr innerIndent binding}\n{indent}{renderExpr indent body}"
            | _ ->
                $"let {name} = {renderExpr indent binding}\n{indent}{renderExpr indent body}"
        | RecordConstruction fields ->
            let fieldStr =
                fields
                |> List.map (fun (name, expr) -> $"{cleanParamName name} = {renderExpr indent expr}")
                |> String.concat "; "
            $"{{ {fieldStr} }}"
        | MatchExpr (scrutinee, cases) ->
            let caseStr =
                cases
                |> List.map (fun (pattern, body) -> $"\n{indent}| {pattern} -> {renderExpr indent body}")
                |> String.concat ""
            $"match {renderExpr indent scrutinee} with{caseStr}"
        | RawExpr code -> code

    /// Render an expression as a function argument, parenthesizing compound expressions.
    and renderArg (indent: string) (expr: FsExpr) =
        match expr with
        | Identifier _ | Literal _ -> renderExpr indent expr
        | _ -> $"({renderExpr indent expr})"

    /// Render a single FsDecl node to the StringBuilder at the given indentation level
    let rec private renderDecl (sb: StringBuilder) (indent: int) (decl: FsDecl) =
        let prefix = String.replicate indent "    "
        match decl with
        | Module (name, comment, decls) ->
            sb.AppendLine($"module {name}") |> ignore
            sb.AppendLine() |> ignore
            sb.AppendLine($"// Generated by Farscape — {comment}") |> ignore
            sb.AppendLine() |> ignore
            for d in decls do
                renderDecl sb 0 d

        | XmlDoc text ->
            sb.AppendLine($"{prefix}    /// {text}") |> ignore

        | Comment text ->
            sb.AppendLine($"{prefix}{text}") |> ignore

        | BlankLine ->
            sb.AppendLine() |> ignore

        | LetBinding (name, params', retType, body, attributes) ->
            for attr in attributes do
                sb.AppendLine($"{prefix}    [<{attr}>]") |> ignore
            let paramStr =
                if params'.IsEmpty then "()"
                else params' |> List.map renderParam |> String.concat " "
            sb.AppendLine($"{prefix}    let {name} {paramStr} : {renderType retType} =") |> ignore
            let bodyIndent = $"{prefix}        "
            sb.Append($"{bodyIndent}{renderExpr bodyIndent body}") |> ignore
            sb.AppendLine() |> ignore
            sb.AppendLine() |> ignore

        | LiteralBinding (name, value) ->
            sb.AppendLine($"{prefix}[<Literal>]") |> ignore
            sb.AppendLine($"{prefix}let {name} = {value}") |> ignore

        | RecordType (name, fields, doc, attributes) ->
            match doc with
            | Some d -> sb.AppendLine($"{prefix}/// {d}") |> ignore
            | None -> ()
            for attr in attributes do
                sb.AppendLine($"{prefix}[<{attr}>]") |> ignore
            sb.AppendLine($"{prefix}type {name} = {{") |> ignore
            for (fname, ftype) in fields do
                sb.AppendLine($"{prefix}    {cleanParamName fname}: {renderType ftype}") |> ignore
            sb.AppendLine($"{prefix}}}") |> ignore
            sb.AppendLine() |> ignore

        | EnumType (name, values, doc, isFlags) ->
            match doc with
            | Some d -> sb.AppendLine($"{prefix}/// {d}") |> ignore
            | None -> ()
            if isFlags then
                sb.AppendLine($"{prefix}[<System.Flags>]") |> ignore
            sb.AppendLine($"{prefix}type {name} =") |> ignore
            for (vname, vval) in values do
                sb.AppendLine($"{prefix}    | {cleanParamName vname} = {vval}L") |> ignore
            sb.AppendLine() |> ignore

        | SubModule (name, decls) ->
            sb.AppendLine($"{prefix}module {name} =") |> ignore
            for d in decls do
                renderDecl sb (indent + 1) d
            sb.AppendLine() |> ignore

        | ExplicitLayoutRecord (name, fields, sizeBytes, doc) ->
            match doc with
            | Some d -> sb.AppendLine($"{prefix}/// {d}") |> ignore
            | None -> ()
            sb.AppendLine($"{prefix}[<StructLayout(LayoutKind.Explicit, Size = {sizeBytes})>]") |> ignore
            sb.AppendLine($"{prefix}[<Struct>]") |> ignore
            sb.AppendLine($"{prefix}type {name} = {{") |> ignore
            for f in fields do
                sb.AppendLine($"{prefix}    [<FieldOffset({f.OffsetBytes})>]") |> ignore
                sb.AppendLine($"{prefix}    {f.Name}: {renderType f.Type}") |> ignore
            sb.AppendLine($"{prefix}}}") |> ignore
            sb.AppendLine() |> ignore

        | DelegateType (name, parameters, returnType, doc) ->
            match doc with
            | Some d -> sb.AppendLine($"{prefix}/// {d}") |> ignore
            | None -> ()
            let paramStr =
                if parameters.IsEmpty then "unit"
                else
                    parameters
                    |> List.map (fun (pname, ptype) -> $"{pname}: {renderType ptype}")
                    |> String.concat " * "
            sb.AppendLine($"{prefix}type {name} = delegate of {paramStr} -> {renderType returnType}") |> ignore
            sb.AppendLine() |> ignore

        | OpenModule name ->
            sb.AppendLine($"{prefix}open {name}") |> ignore


    /// Render a complete FsDecl tree to an F# source string.
    /// This is the single entry point; the ONLY StringBuilder in Farscape.
    let render (decl: FsDecl) : string =
        let sb = StringBuilder()
        renderDecl sb 0 decl
        sb.ToString().TrimEnd() + "\n"
