namespace Farscape.Core

open System.Text
open CodeAST

/// Renders FsDecl AST nodes to F# source code strings.
///
/// This is the ONLY module in Farscape that uses StringBuilder.
/// Every other module produces FsDecl values — typed, inspectable, testable.
module CodeRenderer =

    /// Render an FsType to its F# string representation
    let rec renderType = function
        | Named n -> n
        | Generic (outer, inner) -> $"{outer}<{renderType inner}>"
        | Unit -> "unit"

    /// Render an FsParam to "(name: type)" form
    let renderParam (p: FsParam) = $"({p.Name}: {renderType p.Type})"

    /// Render an FsExpr to its F# string representation.
    /// The indent parameter is the continuation indent for multi-line expressions.
    let rec renderExpr (indent: string) = function
        | DefaultOf ty -> $"Unchecked.defaultof<{renderType ty}>"
        | FunctionCall (mod', name, args) ->
            let argStr = args |> List.map (renderExpr indent) |> String.concat " "
            if mod' = "" then $"{name} {argStr}"
            else $"{mod'}.{name} {argStr}"
        | Identifier name -> name
        | TypeConversion (target, expr) -> $"{target} ({renderExpr indent expr})"
        | MethodCall (expr, method') -> $"{method'} ({renderExpr indent expr})"
        | IfThenElse (cond, thenE, elseE) ->
            $"if {renderExpr indent cond} then {renderExpr indent thenE}\n{indent}else {renderExpr indent elseE}"
        | Comparison (left, op, right) -> $"{renderExpr indent left} {op} {renderExpr indent right}"
        | Literal s -> s
        | ResultOk expr ->
            match expr with
            | Identifier _ | Literal _ -> $"Ok {renderExpr indent expr}"
            | _ -> $"Ok ({renderExpr indent expr})"
        | ResultError expr ->
            match expr with
            | Identifier _ | Literal _ -> $"Error {renderExpr indent expr}"
            | _ -> $"Error ({renderExpr indent expr})"
        | LetIn (name, binding, body) ->
            $"let {name} = {renderExpr indent binding}\n{indent}{renderExpr indent body}"

    /// Render a single FsDecl node to the StringBuilder at the given indentation level
    let rec private renderDecl (sb: StringBuilder) (indent: int) (decl: FsDecl) =
        let prefix = String.replicate indent "    "
        match decl with
        | Module (name, comment, decls) ->
            sb.AppendLine($"module {name}") |> ignore
            sb.AppendLine() |> ignore
            sb.AppendLine($"// Generated by Farscape — Fidelity binding for {comment}") |> ignore
            sb.AppendLine("// Alex provides platform-specific MLIR implementations for these bindings.") |> ignore
            sb.AppendLine() |> ignore
            for d in decls do
                renderDecl sb 0 d

        | XmlDoc text ->
            sb.AppendLine($"{prefix}    /// {text}") |> ignore

        | Comment text ->
            sb.AppendLine($"{prefix}{text}") |> ignore

        | BlankLine ->
            sb.AppendLine() |> ignore

        | LetBinding (name, params', retType, body) ->
            let paramStr =
                if params'.IsEmpty then "()"
                else params' |> List.map renderParam |> String.concat " "
            sb.AppendLine($"{prefix}    let {name} {paramStr} : {renderType retType} =") |> ignore
            let bodyIndent = $"{prefix}        "
            sb.Append($"{bodyIndent}{renderExpr bodyIndent body}") |> ignore
            sb.AppendLine() |> ignore
            sb.AppendLine() |> ignore

        | LiteralBinding (name, value) ->
            sb.AppendLine($"{prefix}[<Literal>]") |> ignore
            sb.AppendLine($"{prefix}let {name} = {value}") |> ignore

        | RecordType (name, fields, doc) ->
            match doc with
            | Some d -> sb.AppendLine($"{prefix}/// {d}") |> ignore
            | None -> ()
            sb.AppendLine($"{prefix}type {name} = {{") |> ignore
            for (fname, ftype) in fields do
                sb.AppendLine($"{prefix}    {fname}: {renderType ftype}") |> ignore
            sb.AppendLine($"{prefix}}}") |> ignore
            sb.AppendLine() |> ignore

        | EnumType (name, values, doc) ->
            match doc with
            | Some d -> sb.AppendLine($"{prefix}/// {d}") |> ignore
            | None -> ()
            sb.AppendLine($"{prefix}type {name} =") |> ignore
            for (vname, vval) in values do
                sb.AppendLine($"{prefix}    | {vname} = {vval}L") |> ignore
            sb.AppendLine() |> ignore

    /// Render a complete FsDecl tree to an F# source string.
    /// This is the single entry point — the ONLY StringBuilder in Farscape.
    let render (decl: FsDecl) : string =
        let sb = StringBuilder()
        renderDecl sb 0 decl
        sb.ToString().TrimEnd() + "\n"
