namespace Farscape.Core

open Types

/// Generates BAREWire StructDescriptor source code for ABI-critical structs.
///
/// Farscape emits source text referencing BAREWire types (no compile-time dependency).
/// The generated Descriptors.fs file can be compiled in a BAREWire-aware project
/// to enable memory layout validation across heterogeneous processors.
module DescriptorGenerator =

    /// Map an F# type name (from TypeMapper) to its NTUKind constructor string.
    /// Returns the source-level representation, e.g., "NTUKind.NTUuint32".
    let mapToNTUKindString (fsType: string) : string =
        match fsType with
        | "int8"      -> "NTUKind.NTUint8"
        | "int16"     -> "NTUKind.NTUint16"
        | "int32"     -> "NTUKind.NTUint32"
        | "int64"     -> "NTUKind.NTUint64"
        | "byte"      -> "NTUKind.NTUuint8"
        | "uint16"    -> "NTUKind.NTUuint16"
        | "uint32"    -> "NTUKind.NTUuint32"
        | "uint64"    -> "NTUKind.NTUuint64"
        | "float32"   -> "NTUKind.NTUfloat32"
        | "float"     -> "NTUKind.NTUfloat64"
        | "bool"      -> "NTUKind.NTUbool"
        | "nativeint"  -> "NTUKind.NTUint64"   // pointer-width, approximation
        | "unativeint" -> "NTUKind.NTUuint64"   // pointer-width, approximation
        | _           -> $"NTUKind.NTUuint8 (* unmapped: {fsType} *)"

    /// Render a single field descriptor as F# source.
    let private renderField (indent: string) (name: string) (offsetBytes: int) (ntuKind: string) (doc: string option) : string =
        let docStr = match doc with Some d -> $"Some \"{d}\"" | None -> "None"
        $"{indent}{{ Name = \"{name}\"; Offset = {offsetBytes}; Type = {ntuKind}\n" +
        $"{indent}  Access = AccessKind.ReadWrite; BitFields = [||]; Documentation = {docStr} }}"

    /// Generate BAREWire StructDescriptor source code for a list of ABI-critical structs.
    /// Each struct must have layout info from clang.
    let generate
        (structs: (CppParser.StructDecl * CppParser.StructLayoutInfo) list)
        (namespace': string)
        (typedefMap: Map<string, string>) (model: PlatformABI)
        (opaqueHandles: Set<string>)
        : string =

        let mapType = FidelityCodeGenerator.mapCTypeToFidelityType typedefMap model opaqueHandles

        let sb = System.Text.StringBuilder()
        sb.AppendLine($"module {namespace'}") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("// Generated by Farscape — BAREWire struct descriptors for ABI validation") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("open BAREWire.Hardware") |> ignore
        sb.AppendLine() |> ignore

        for (s, layout) in structs do
            let fieldPairs = List.zip s.Fields layout.FieldOffsetsBits
            let sizeBytes = layout.SizeBits / 8
            let alignBytes = layout.AlignmentBits / 8

            let docStr = match s.Documentation with Some d -> $"Some \"{d}\"" | None -> "None"

            sb.AppendLine($"let {s.Name} : StructDescriptor =") |> ignore
            sb.AppendLine($"    {{ Name = \"{s.Name}\"") |> ignore
            sb.AppendLine($"      Layout =") |> ignore
            sb.AppendLine($"        {{ Size = {sizeBytes}; Alignment = {alignBytes}") |> ignore
            sb.AppendLine($"          Fields = [|") |> ignore

            for (field, offsetBits) in fieldPairs do
                let fsType = mapType field.Type |> CodeRenderer.renderType
                let ntuKind = mapToNTUKindString fsType
                sb.AppendLine(renderField "            " field.Name (offsetBits / 8) ntuKind None) |> ignore

            sb.AppendLine($"          |] }}") |> ignore
            sb.AppendLine($"      Documentation = {docStr} }}") |> ignore
            sb.AppendLine() |> ignore

        sb.ToString().TrimEnd() + "\n"
